# OpTiMSoC requires Ubuntu 16.04
# Travis supports this OS only in a docker environment
# See Dockerfile for the full build instructions
sudo: required
language: cpp

services:
      - docker

script:
    - docker build .

